/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.DatabaseAccess;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;  
import java.io.File;
import java.io.FileInputStream;  
import java.io.FilenameFilter;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javazoom.jl.player.Player;

/**
 * Code for GUI
 */

public class GUI extends javax.swing.JFrame {
    
    public static int safeLongToInt(long l) {
        if (l < Integer.MIN_VALUE || l > Integer.MAX_VALUE) {
            throw new IllegalArgumentException
                (l + " cannot be cast to int without changing its value.");
        }
        return (int) l;
    }
    public static int[] convertIntegers(List<Integer> integers){
        int[] ret = new int[integers.size()];
        Iterator<Integer> iterator = integers.iterator();
        for (int i = 0; i < ret.length; i++)
        {
            ret[i] = iterator.next().intValue();
        }
        return ret;
    }

    //File newfile = new File("C:\\Users\\Mitchell\\Documents\\leftright.wav");

    static File newfile = new File("F:\\Jeffrey\\Music\\Songs\\wav\\0\\Dynamite.wav");
    Clip clip = null;
    boolean x = true;
    Thread thread = new Thread(new thread1());
    long playloc = 0;
    static DatabaseAccess dba = new DatabaseAccess();
    static Connection con = dba.startconnection("orcl");
    
    public class thread1 implements Runnable{
        public void run(){
            while ((clip.getMicrosecondPosition() < clip.getMicrosecondLength())&&!thread.isInterrupted()){
                long sprog = (clip.getMicrosecondPosition());
                long slength = (clip.getMicrosecondLength());
                String seconds = Long.toString((sprog/1000000)%60);
                long minutes = ((sprog/1000000)-Integer.parseInt(seconds))/60;
                long position = (long)(sprog*1000/slength); //aduio progress abr is 1000 units long
                System.out.println(sprog + " / " + slength + " * 1000 = " + position);
                audioProgressSlider1.setValue(safeLongToInt(position));
                if(Integer.parseInt(seconds)<10){
                    seconds = "0" + seconds;
                }
                currenttime.setText(minutes+":"+seconds);
                long totminutes = ((slength/1000000)-(slength/1000000)%60)/60;
                String totseconds = Long.toString((slength/1000000)%60);
                if(Integer.parseInt(totseconds)<10){
                    totseconds = "0" + totseconds;
                }
                timeleft.setText(totminutes + ":" + totseconds);
//                                audioProgressSlider1.setValue(i); //Set value
//				audioProgressSlider1.repaint(); //Refresh graphics
                try{Thread.sleep(50);} //Sleep 50 milliseconds
                catch (InterruptedException err){
                    return;
                }
            }
        }
    }
    /**
     * Creates new form newGUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        mood5 = new javax.swing.JCheckBox();
        mood6 = new javax.swing.JCheckBox();
        albumtext = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lyrictext = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mood4 = new javax.swing.JCheckBox();
        mood1 = new javax.swing.JCheckBox();
        mood0 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        title2 = new javax.swing.JTextField();
        artist2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mood2 = new javax.swing.JCheckBox();
        searchButton2 = new javax.swing.JButton();
        mood3 = new javax.swing.JCheckBox();
        length2 = new javax.swing.JTextField();
        mood7 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        year1 = new javax.swing.JCheckBox();
        year2 = new javax.swing.JCheckBox();
        year3 = new javax.swing.JCheckBox();
        year5 = new javax.swing.JCheckBox();
        year6 = new javax.swing.JCheckBox();
        year7 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        year4 = new javax.swing.JCheckBox();
        year0 = new javax.swing.JCheckBox();
        genreselect = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lyrics = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        playpause1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        stopButton1 = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        outputtable = new javax.swing.JTable();
        audioProgressSlider1 = new javax.swing.JSlider();
        timeleft = new javax.swing.JLabel();
        currenttime = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        viewSongs = new javax.swing.JMenuItem();
        addSongs = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        loadClassifier = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);

        jPanel2.setFocusCycleRoot(true);
        jPanel2.setMaximumSize(new java.awt.Dimension(3840, 2160));
        jPanel2.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setMinimumSize(new java.awt.Dimension(1024, 576));
        jSplitPane2.setName(""); // NOI18N

        jPanel3.setToolTipText("");
        jPanel3.setAutoscrolls(true);
        jPanel3.setMaximumSize(new java.awt.Dimension(320, 2160));
        jPanel3.setMinimumSize(new java.awt.Dimension(320, 1280));
        jPanel3.setName(""); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 720));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Search");

        mood5.setText("Mood 5");

        mood6.setText("Mood 6");

        albumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumtextjTextField1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Lyrics");

        lyrictext.setText("(type any part of a song's lyrics you remember here)");
        lyrictext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lyrictextjTextField2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Album");

        mood4.setText("Mood 4");
        mood4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mood4jCheckBox5ActionPerformed(evt);
            }
        });

        mood1.setText("Mood 1");

        mood0.setText("Mood 0");

        jLabel21.setText("Artist");

        jLabel22.setText("Mood(s):");

        title2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title2ActionPerformed(evt);
            }
        });

        artist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist2artistActionPerformed(evt);
            }
        });

        jLabel23.setText("Length (min:sec)");

        mood2.setText("Mood 2");

        searchButton2.setText("Search");
        searchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton2searchButtonActionPerformed(evt);
            }
        });

        mood3.setText("Mood 3");

        length2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                length2lengthActionPerformed(evt);
            }
        });

        mood7.setText("Mood 7");

        jLabel24.setText("Song Name");

        jLabel3.setText("Genre(s)");

        year1.setText("1950-1959");
        year1.setToolTipText("");

        year2.setText("1960-1969");

        year3.setText("1970-1979");
        year3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year3ActionPerformed(evt);
            }
        });

        year5.setText("1990-1999");

        year6.setText("2000-2009");

        year7.setText("2010-2014");

        jLabel4.setText("Year(s) Released");

        year4.setText("1980-1989");
        year4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year4jCheckBox5ActionPerformed(evt);
            }
        });

        year0.setText("1940-1949");
        year0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year0ActionPerformed(evt);
            }
        });

        genreselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One:", "Alternative", "Christian", "Classical", "Country", "Dance", "Electronic", "Gospel", "Hip Hop", "Holiday", "Pop", "R&B", "Rap", "Rock", "Soul", "Soundtrack", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mood0)
                                .addGap(18, 18, 18)
                                .addComponent(mood4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mood1)
                                .addGap(18, 18, 18)
                                .addComponent(mood5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mood2)
                                .addGap(18, 18, 18)
                                .addComponent(mood6))
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mood3)
                                .addGap(18, 18, 18)
                                .addComponent(mood7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(year0)
                                .addGap(18, 18, 18)
                                .addComponent(year4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(year1)
                                .addGap(18, 18, 18)
                                .addComponent(year5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(year2)
                                .addGap(18, 18, 18)
                                .addComponent(year6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(year3)
                                .addGap(18, 18, 18)
                                .addComponent(year7))
                            .addComponent(jLabel4)
                            .addComponent(jLabel18)
                            .addComponent(jLabel24)
                            .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)
                                .addComponent(albumtext)
                                .addComponent(artist2)
                                .addComponent(jLabel19)
                                .addComponent(lyrictext)
                                .addComponent(length2)))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(genreselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton2)
                        .addGap(32, 32, 32))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(albumtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(length2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lyrictext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mood0)
                    .addComponent(mood4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mood1)
                    .addComponent(mood5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mood2)
                    .addComponent(mood6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mood3)
                    .addComponent(mood7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year0)
                    .addComponent(year4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year1)
                    .addComponent(year5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year2)
                    .addComponent(year6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year3)
                    .addComponent(year7))
                .addContainerGap(671, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        jLabel25.setText("Lyrics");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        lyrics.setViewportView(jTextArea2);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Results");

        playpause1.setText("Play");
        playpause1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playpauseActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/out.png"))); // NOI18N

        stopButton1.setText("Stop");
        stopButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButton1ActionPerformed(evt);
            }
        });

        outputtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Song Name", "Artist", "Album", "Length", "Overall Mood", "Genre", "Year Released"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outputtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputtableMouseClicked(evt);
            }
        });
        table.setViewportView(outputtable);

        audioProgressSlider1.setMaximum(1000);
        audioProgressSlider1.setValue(0);

        timeleft.setText("0:00");

        currenttime.setText("0:00");

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(audioProgressSlider1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(table, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(currenttime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeleft))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(playpause1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stopButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lyrics, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(audioProgressSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currenttime)
                            .addComponent(timeleft))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playpause1)
                            .addComponent(stopButton1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lyrics, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jSplitPane2.setRightComponent(jPanel4);

        jPanel2.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(3840, 21));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1024, 21));
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("Songs");

        viewSongs.setText("View All");
        viewSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSongsActionPerformed(evt);
            }
        });
        jMenu1.add(viewSongs);

        addSongs.setText("Add New");
        jMenu1.add(addSongs);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Advanced");

        loadClassifier.setText("Load Classifier");
        jMenu2.add(loadClassifier);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void viewSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSongsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSongsActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void stopButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButton1ActionPerformed
        // TODO add your handling code here:
        playpause1.setText("Play");
        x = true;
        playloc = 0;
        if((clip != null)){
            clip.stop();
            clip.setMicrosecondPosition(0);
        }
        if(!thread.isInterrupted()&&thread.isAlive()){
            thread.interrupt();
        }
        currenttime.setText("0:00");
        audioProgressSlider1.setValue(0);
    }//GEN-LAST:event_stopButton1ActionPerformed

    private void playpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playpauseActionPerformed
        // TODO add your handling code here:
        if(x == true){
            playpause1.setText("Pause");
            x = false;
            System.out.println(x);
            try{
                clip = AudioSystem.getClip();
                // getAudioInputStream() also accepts a File or InputStream
                AudioInputStream ais = AudioSystem.getAudioInputStream(newfile);
                clip.open(ais);
                clip.setMicrosecondPosition(playloc);
                clip.start();
                System.out.println(thread.isInterrupted());
                if(!thread.isAlive()){
                    thread = new Thread(new thread1());
                    thread.start();
                }
                else if(thread.isInterrupted()){
                    thread.interrupted();
                }

            } catch (Exception e){
                e.printStackTrace();
            }
        } else {
            if(!thread.isInterrupted()){
                thread.interrupt();
                System.out.println("Interrupted!");
            }
            playpause1.setText("Play");
            playloc = clip.getMicrosecondPosition();
            clip.stop();
            x = true;
        }
    }//GEN-LAST:event_playpauseActionPerformed

    private void year0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year0ActionPerformed

    private void year4jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year4jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year4jCheckBox5ActionPerformed

    private void year3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year3ActionPerformed

    private void length2lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_length2lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_length2lengthActionPerformed

    private void searchButton2searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton2searchButtonActionPerformed
        // create the appropriate WHERE clause
        ArrayList<Integer> moodt = new ArrayList<Integer>();
        if(mood0.isSelected()){
            moodt.add(0);
        }
        if(mood1.isSelected()){
            moodt.add(1);
        }
        if(mood2.isSelected()){
            moodt.add(2);
        }
        if(mood3.isSelected()){
            moodt.add(3);
        }
        if(mood4.isSelected()){
            moodt.add(4);
        }
        if(mood5.isSelected()){
            moodt.add(5);
        }
        if(mood6.isSelected()){
            moodt.add(6);
        }
        if(mood7.isSelected()){
            moodt.add(7);
        }
        int[] moods = convertIntegers(moodt);
        if(!title2.getText().equals("")){
            
        }
        if(!artist2.getText().equals("")){
            
        }
        int seconds = 0;
        if(!length2.getText().equals("")){
            int index = length2.getText().indexOf(":");
            seconds = Integer.parseInt(length2.getText().substring(index+1)) + Integer.parseInt(length2.getText().substring(0,index))*60;
        }
        //get results from database
        try{
            dba.getSearchResults(con,moods,seconds);
        } catch (SQLException e){
            e.printStackTrace();
        }
        
        //output to table
        for(int i = 0; i<25; i++){
            for(int j = 0; j<6; j++){
                outputtable.setValueAt("test",i,j);
            }
        }
    }//GEN-LAST:event_searchButton2searchButtonActionPerformed

    private void artist2artistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist2artistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artist2artistActionPerformed

    private void mood4jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mood4jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mood4jCheckBox5ActionPerformed

    private void lyrictextjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lyrictextjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lyrictextjTextField2ActionPerformed

    private void albumtextjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumtextjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumtextjTextField1ActionPerformed

    private void title2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title2ActionPerformed

    private void outputtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputtableMouseClicked
        // TODO add your handling code here:
        int row = outputtable.getSelectedRow();
        System.out.println(row);
        String[] selectrow = new String[6];
        for(int i = 0; i<6; i++){
            selectrow[i] = String.valueOf(outputtable.getModel().getValueAt(row, i));
            System.out.println(selectrow[i]);
        }
        
    }//GEN-LAST:event_outputtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        String mp3mdir = "F:\\Jeffrey\\Music\\Songs"; //directory for MP3
        File musicdir = new File(mp3mdir);
        //array of MP3 files (to get artist and title)
        File[] allmp3files = musicdir.listFiles(new FilenameFilter(){ //use filter to make sure we don't read any album art files (.jpg)
            @Override
            public boolean accept(File dir, String name){
                if(name.toLowerCase().endsWith(".jpg")){
                    return false;
                }
                return true;
            }
        }
        );
        
        String wavmdir = "F:\\Jeffrey\\Music\\Songs\\wav\\0"; //directory for WAV
        musicdir = new File(wavmdir);
        //array of WAV files (to play)
        File[] allwavfiles = musicdir.listFiles(new FilenameFilter(){ //use filter to make sure we don't read any album art files (.jpg)
            @Override
            public boolean accept(File dir, String name){
                if(name.toLowerCase().endsWith(".jpg")){
                    return false;
                }
                return true;
            }
        }
        );
        
        
        
        //newfile = new File("C:\\Users\\Mitchell\\Documents\\leftright.wav");

        newfile = new File("F:\\Jeffrey\\Music\\Songs\\wav\\0\\Dynamite.wav");
        
        int[] moodtest = {0,1,2,3,4,5,6,7,-1,-1,-1};
        AudioWaveformCreator awc = new AudioWaveformCreator(newfile, "out.png", moodtest);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addSongs;
    private javax.swing.JTextField albumtext;
    private javax.swing.JTextField artist2;
    private javax.swing.JSlider audioProgressSlider1;
    private javax.swing.JLabel currenttime;
    private javax.swing.JComboBox genreselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField length2;
    private javax.swing.JMenuItem loadClassifier;
    private javax.swing.JScrollPane lyrics;
    private javax.swing.JTextField lyrictext;
    private javax.swing.JCheckBox mood0;
    private javax.swing.JCheckBox mood1;
    private javax.swing.JCheckBox mood2;
    private javax.swing.JCheckBox mood3;
    private javax.swing.JCheckBox mood4;
    private javax.swing.JCheckBox mood5;
    private javax.swing.JCheckBox mood6;
    private javax.swing.JCheckBox mood7;
    private javax.swing.JTable outputtable;
    private javax.swing.JButton playpause1;
    private javax.swing.JButton searchButton2;
    private javax.swing.JButton stopButton1;
    private javax.swing.JScrollPane table;
    private javax.swing.JLabel timeleft;
    private javax.swing.JTextField title2;
    private javax.swing.JMenuItem viewSongs;
    private javax.swing.JCheckBox year0;
    private javax.swing.JCheckBox year1;
    private javax.swing.JCheckBox year2;
    private javax.swing.JCheckBox year3;
    private javax.swing.JCheckBox year4;
    private javax.swing.JCheckBox year5;
    private javax.swing.JCheckBox year6;
    private javax.swing.JCheckBox year7;
    // End of variables declaration//GEN-END:variables
}
